name: Publish to Cargo

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: 'publish'
    steps:
      - uses: actions/checkout@v4
        with:
          # get git tags info
          fetch-depth: 0
      
      - name: Run publish-action
        uses: tu6ge/publish-action@v0.4.6
        env:
          # This can help you tagging the github repository
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # This can help you publish to crates.io
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
